

--- CREATION OF TABLESPACE

DROP TABLESPACE IA643_TBS INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE IA643_TBS
DATAFILE 'IA643_dat.dat' SIZE 500K REUSE
AUTOEXTEND ON NEXT 300K MAXSIZE 100M;

---CREATION OF PROFILE FOR CALLED Develop_prof

DROP PROFILE Develop_prof CASCADE;
CREATE PROFILE Develop_prof LIMIT
SESSIONS_PER_USER       UNLIMITED
CPU_PER_SESSION         UNLIMITED
CPU_PER_CALL              3000
CONNECT_TIME             180
LOGICAL_READS_PER_SESSION   DEFAULT 
LOGICAL_READS_PER_CALL     1000 
PRIVATE_SGA               15K
COMPOSITE_LIMIT            5000000
FAILED_LOGIN_ATTEMPTS      4
PASSWORD_LIFE_TIME         90
PASSWORD_REUSE_TIME        30
PASSWORD_REUSE_MAX         3
PASSWORD_LOCK_TIME         1
PASSWORD_GRACE_TIME        3;

---CREATION OF USERS

---CREATING USER Joe Smith

DROP USER JSmith CASCADE;
CREATE USER JSmith IDENTIFIED BY JSmith
DEFAULT TABLESPACE IA643_TBS
QUOTA 10M ON IA643_TBS
TEMPORARY TABLESPACE TEMP
PROFILE Develop_prof
PASSWORD EXPIRE
ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE TO JSmith;

---CREATING USER Sam Houston

DROP USER SHouston CASCADE;
CREATE USER SHouston IDENTIFIED BY SHouston
DEFAULT TABLESPACE IA643_TBS
QUOTA 10M ON IA643_TBS
TEMPORARY TABLESPACE TEMP
PROFILE Develop_prof
PASSWORD EXPIRE
ACCOUNT UNLOCK; 
GRANT CONNECT, RESOURCE TO SHouston;

--- CREATING USER Stephanie Clark

DROP USER SClark CASCADE;
CREATE USER SClark IDENTIFIED BY SClark
DEFAULT TABLESPACE IA643_TBS
QUOTA 10M ON IA643_TBS
TEMPORARY TABLESPACE TEMP
PROFILE Develop_prof
PASSWORD EXPIRE
ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE TO SClark;


-- CREATING USER Bob Johnson

DROP USER BJohnson CASCADE;
CREATE USER BJohnson IDENTIFIED BY BJohnson
DEFAULT TABLESPACE IA643_TBS
QUOTA 10M ON IA643_TBS
TEMPORARY TABLESPACE TEMP
PROFILE Develop_prof
PASSWORD EXPIRE
ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE TO BJohnson;

---ALTER PROFILE TO ADD PASSWORD VERIFICATION FUNCTION

ALTER PROFILE Develop_prof LIMIT PASSWORD_VERIFY_FUNCTION dd_pwd_fun;

/*
---ORACLE VERIFICATION FUNCTION dd_pwd_fun
CREATE OR REPLACE FUNCTION dd_pwd_fun(P_userid varchar2, P_password varchar2,
 P_old_password varchar2) RETURN BOOLEAN IS
PWD_STR VARCHAR2(255);
condition INTEGER;
numberarray VARCHAR2(20);
lowercasecharacterarray VARCHAR2(56);
uppercasecharacterarray VARCHAR2(56);
String_length INTEGER;
BEGIN
condition := 0;
numberarray := '0123456789';
lowercasecharacterarray := 'abcdefghijklmnopqrstuvwxyz';
uppercasecharacterarray := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
String_length := LENGTH(P_password);
PWD_STR := UPPER(P_password);
IF LENGTH(PWD_STR) < 8 THEN 
RETURN FALSE; 
END IF;
-- -checking for at least one digit
FOR i IN 1..10 LOOP
FOR j IN 1.. String_length LOOP
IF SUBSTR(P_password,j,1) = SUBSTR(numberarray,i,1) THEN
condition := 1;
END IF;
END LOOP;
END LOOP;
IF condition = 1 then
---checking for lower case letter
FOR i IN 1..LENGTH(lowercasecharacterarray) LOOP
FOR j IN 1.. String_length LOOP
IF SUBSTR(P_password,j,1) = SUBSTR(lowercasecharacterarray,i,1) THEN
condition := 2;
END IF;
END LOOP;
END LOOP;
END IF;
IF condition=2 then
---for checking uppercase character
FOR i IN 1..LENGTH(uppercasecharacterarray) LOOP
FOR j IN 1.. String_length LOOP
IF SUBSTR(P_password,j,1) = SUBSTR(uppercasecharacterarray,i,1) THEN
condition:= 3;
END IF;
END LOOP;
END LOOP;
END IF;
IF condition = 3 then
---checking for three or more consecutive letters
FOR i IN 1..LENGTH(PWD_STR)-2 LOOP
IF INSTR(LOWER(P_userid),SUBSTR(LOWER(PWD_STR),i,3)) > 0 THEN
RETURN FALSE;
END IF;
END LOOP;
END IF;
IF condition = 4 THEN
RETURN FALSE;
ELSE
IF condition =3 THEN
RETURN TRUE;
ELSE
RETURN FALSE;
END IF;
END IF;
END;
/

Show errors;
*/







